---
title: "Curriculum Vitae"
format:
  html:
    toc: true
  pdf:
    author: Ryan Zomorrodi
    pdf-engine: weasyprint
css: _assets/cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
rzomor2\@uic.edu
:::

::: no-print
*Last updated June 5, 2025*
:::

## Education

**Master of Science -- Biostatistics**  
*University of Illinois Chicago* [*Aug 2023 --- May 2025*]{.cvdate}

-   GPA: 4.00

**Bachelor of Science -- Biological Science**  
*University of Illinois Chicago* [*Aug 2019 --- May 2023*]{.cvdate}

-   Minors: Computer Science & Public Health
-   Graudated with Highest Distinction
-   Honors College
-   GPA: 4.00

## Work Experience

**Research Associate**  
*Children's Environmental Health Initiative* [Jun 2023 --- Present]{.cvdate}

-   Performed geospatial analysis of hospital and physician accessibility utilizing two-step floating catchment area methods.
-   Developed Rate Stabilizing Toolbox in Python to generate generating reliable, local-level age-standardized measures of chronic disease using the restricted univariate conditional autoregressive (UCAR) bayesian model.
-   Generated measures of hurricane exposure for 15 severe storms in order facilitate analysis of hurricane exposure effects on mortality amongst elderly individuals.
-   Instructed state, tribal, and local public health professionals on the use of GIS to assess and address chronic health disparities.

## Software

[**socratadata**](project/socratadata/index.qmd)  
*R package API wrapper that utilzes Rust to parse Socrata datasets into R dataframes. Also features support for Socrata Query Langauge (SoQL) and the Socrata Discovery API.*  
[**arcpygris**](https://github.com/ryanzomorrodi/arcpygris)  
*Python toolbox for downloading Census boundaries into an ArcGIS Pro project. Inspired heavily by the R package tigris.*  
[**sasquatch**](project/sasquatch/index.qmd)  
*R package that bridges SAS and R. Utilizes the Python package SASPy to enable transfer of data between R and SAS, interactive SAS evaluation, basic remote SAS client file management, and rendering of SAS within quarto/rmarkdown documents.*  
[**healthatlas**](project/healthatlas/index.qmd)  
*R package API wrapper for Metopio health atlas data. Allows for easy exploration of health atlas datasets and metadata.*  
[**centr**](project/centr/index.qmd)  
*R package that designed to calculate planar or geodesic weighted mean or median spatial centers.*  
[**Rate Stabilizing Toolbox**](project/rst/index.qmd)  
*Python toolbox for generating reliable, local-level age-standardized measures of chronic disease using the restricted univariate conditional autoregressive (UCAR) bayesian model.*  

## Presentations & Workshops

**Enhancing Local Level Surveillance and Data Visualization of Health Outcomes: Introducing a Set of Rate Stabilizing Tools**  
*Council of State and Territorial Epidemiologists* [*10 Jun 2025*]{.cvdate}  
**Enhancing Data to Action: Approaches for Using Maps to Address Chronic Disease**  
*Council of State and Territorial Epidemiologists* [*9 Jun 2025*]{.cvdate}  
**Encounter with sasquatch: Using SAS, R, and Quarto together**  
*SAS Open Source Community of Practice* [*25 May 2025*]{.cvdate}  
[Presentation Link](https://ryanzomorrodi.github.io/talk-sas-cop-sasquatch/)  
**Using GIS to Study Social Determinants of Health with R**  
Northern Arizona University Center for Health Equity Research [6 --- 7 Jun 24]{.cvdate}  
[Resource Link](https://ryanzomorrodi.github.io/NAUTraining/)  
**An Introduction to ArcGIS Online Mini-Course**  
*GIS Capacity Building Project* [*17 --- 24 Oct 23*]{.cvdate}  
**A Gentle Introduction to GIS Mini-Course**  
*GIS Capacity Building Project* [*19 --- 26 Sep 23*]{.cvdate}  
**RNA-sequencing analysis of Macrophage Hyperactivation**  
*UIC Undergraduate Research Forum* [*18 Apr 2023*]{.cvdate}  
**Empowering Community Members to Investigate and Address Chicago’s Health Disparities**  
*American Public Health Association* [*9 Nov 2022*]{.cvdate}  
**Empowering Community Members to Investigate and Address Chicago’s Health Disparities**  
*UIC Minority Health Conference* [*8 Apr 2022*]{.cvdate}  
[Recording Link](https://youtu.be/LRhDg3IVbTM?t=340&si=4LewEO33ysc8VRMN)  
**Developing Student Workshops to Increase Community Engagement in Addressing Chicago’s Health Disparities**  
*UIC School of Public Health Research and Scholarship Week Lightning Talks* [*22 Apr 2022*]{.cvdate}  

## Publications

**Significance of IL-34 and SDC-1 in the pathogenesis of RA cells and preclinical models**
*Clinical Immunology* [*May 2023*]{.cvdate}  
[10.1016/j.clim.2023.109635](https://doi.org/10.1016/j.clim.2023.109635)  
**Inhibition of IRAK4 dysregulates SARS-CoV-2 spike proteininduced macrophage inflammatory and glycolytic reprogramming**  
*Cellular and Molecular Life Sciences* [*May 2022*]{.cvdate}  
[10.1007/s00018-022-04329-8](https://doi.org/10.1007/s00018-022-04329-8)  
**Metabolic reprogramming of macrophages instigates CCL21-induced arthritis**  
*Immunology & Cell Biology* [*Dec 2021*]{.cvdate}  
[10.1111/imcb.12512](https://doi.org/10.1111/imcb.12512)  
**Metabolic regulation of RA macrophages is distinct from RA fibroblasts and blockade of glycolysis alleviates inflammatory phenotype in both cell types**  
*Cellular and Molecular Life Sciences* [*Oct 2021*]{.cvdate}  
[10.1007/s00018-021-03978-5](https://doi.org/10.1007/s00018-021-03978-5)  
**Interleukin-34 Reprograms Glycolytic and Osteoclastic Rheumatoid Arthritis Macrophages via Syndecan 1 and Macrophage Colony-Stimulating Factor Receptor**  
*Arthritis & Rheumatology* [*Sep 2021*]{.cvdate}  
[10.1002/art.41792](https://doi.org/10.1002/art.41792)  
**Tofacitinib therapy intercepts macrophage metabolic reprogramming instigated by SARS-CoV-2 Spike protein**  
*European Journal of Immunology* [*Jun 2021*]{.cvdate}  
[10.1002/eji.202049159](https://doi.org/10.1002/eji.202049159)  
**CCL25 and CCR9 is a unique pathway that potentiates pannus formation by remodeling RA macrophages into mature osteoclasts**  
*European Journal of Immunology* [*Jan 2021*]{.cvdate}  
[10.1002/eji.202048681](https://doi.org/10.1002/eji.202048681)  
**IRAK4 inhibition: a promising strategy for treating RA joint inflammation and bone erosion**  
*Cellular & Molecular Immunology* [*May 2020*]{.cvdate}  
[10.1038/s41423-020-0433-8](https://doi.org/10.1038/s41423-020-0433-8)  
**Macrophages are the primary effector cells in IL-7-induced arthritis**  
*Cellular & Molecular Immunology* [*Jun 2019*]{.cvdate}  
[10.1038/s41423-019-0235-z](https://doi.org/10.1038/s41423-019-0235-z)  
**Impact of obesity on autoimmune arthritis and its cardiovascular complications**  
*Autoimmunity Reviews* [*Jun 2018*]{.cvdate}  
[10.1016/j.autrev.2018.02.007](https://doi.org/10.1016/j.autrev.2018.02.007)  

## Teaching Experience

**GIS Training for Surveillance of Heart Disease, Stroke, and Other Chronic Diseases in State Health Departments**  
*GIS Capacity Building Project* [*25 Mar 25 --- 31 Jul 25*]{.cvdate}  
**Hawaii State Department of Health & University of Hawaiʻi GIS Capacity Building**  
*GIS Capacity Building Project* [*28 Jan 25 --- 12 Jun 25*]{.cvdate}  
**Advanced GIS Training for Surveillance of Heart Disease, Stroke and Other Chronic Diseases Among Health Department Staff**  
*GIS Capacity Building Project* [*13 Nov 24 - 29 Jan 25*]{.cvdate}  
**State Health Departments Chronic Disease Surveillance**  
*GIS Capacity Building Project* [*6 Mar 24 --- 31 Jul 24*]{.cvdate}  
**Tribal Epidemiological Centers Chronic Disease Surveillance**  
*GIS Capacity Building Project* [*10 Oct 23 --- 31 Jan 24*]{.cvdate}  

## Honors

**Highest Distinction**  
*UIC Department of Biological Sciences* [*2023*]{.cvdate}  
**Pasteur Prize Nominee**  
*UIC Department of Biological Sciences* [*2023*]{.cvdate}  
**Research Grant**  
*UIC Honors College* [*2022*]{.cvdate}  
**Travel Grant**  
*UIC Honors College* [*2022*]{.cvdate}  
**Maurice Prize**  
*UIC Student Leadership and Civic Engagement* [*2022*]{.cvdate}  
**Undergraduate Most Outstanding Presentation**  
*UIC School of Public Health Research Week* [*2022*]{.cvdate}  
**Chancellor’s Student Service Award**  
*UIC Student Leadership and Civic Engagement* [*2022*]{.cvdate}  
**President’s Volunteer Service Award - Bronze**  
*UIC Student Leadership and Civic Engagement* [*2021*]{.cvdate}  
**1st place - Division 4**  
*Collegiate Chess League* [*2021*]{.cvdate}  
**Chancellor’s Student Service Award**  
*UIC Student Leadership and Civic Engagement* [*2021*]{.cvdate}  
**Research Grant**  
*UIC Honors College* [*2020*]{.cvdate}  

## Professional Membership

**American Public Health Association** [2022]{.cvdate}  
**Harvard Innovation Lab** [2022 --- 2024]{.cvdate}  
**Clinton Global Initiative University Fellowship** [2023]{.cvdate}  
**American Society for Biochemistry and Molecular Biology** [2020 --- 2022]{.cvdate}  

::: {.no-print .hidden}
## Leadership

**Secretary**  
UIC Society of Future Physicians [*2021 --- 2023*]{.cvdate}  
**President**  
Chess Club at UIC [*2021 --- 2023*]{.cvdate}  
**Secretary**  
UIC American Society for Biochemistry and Molecular Biology [*2021 --- 2022*]{.cvdate}  
**Media chairman**  
Spreading Healthcare Awareness through Reciprocal Education (SHARE) [*2020 --- 2022*]{.cvdate}  
**Student leader**  
UIC Student Leadership and Civic Engagement [*2019 --- 2022*]{.cvdate}  
**Chapter representative**  
UIC American Society for Biochemistry and Molecular Biology [*2020 --- 2021*]{.cvdate}  
**Vice-president**  
Chess Club at UIC [*2020 --- 2021*]{.cvdate}  
:::


::: print-only
## References

Available upon request
:::